### ISSUE TITLE
Support for Visual Studio 2022

### ISSUE THREAD

**Issue by pgaessler** [thomaslevesque/AutoRunCustomTool#30]
I can´t find the extension in VS22. We use this extension very often and it would be very helpfull to use in in VS22 too

**Comment by thomaslevesque** [comment]
Hi @pgaessler,

Thanks for reminding me of this.
To be honest, I can't promise anything; supporting VS2022 is likely going to be much more work than for previous VS versions, due to the fact that it's 64 bits.
Also, since it can't support SDK-style projects and only works for "old" csproj, this extension is quickly becoming irrelevant, so I'm not sure it's worth the trouble of maintaining it...
Anyway, I'll look into it

**Comment by dil-sferguson** [comment]
Another vote for us! We use your tool extensively, and would love to continue using it with VS2022. Thanks for your work so far, I hope it's not too much trouble to extend it to work with VS2022

**Comment by thomaslevesque** [comment]
I released the [VS 2022 extension](https://marketplace.visualstudio.com/items?itemName=ThomasLevesque.AutoRunCustomTool2022) today.
Thanks again @ScottyLightnin and @dil-sferguson for your contribution!

**Comment by thomaslevesque** [comment]
Somehow I forgot to make the new extension publicly visible when I published it... It's fixed now.
